number_of_drivers : 4

## rad
origin_offset_angle : [ 5.78966893346455, 0, 0, 0 ]

# 8: position_control, 10: torque_control
control_mode : [ 10, 8, 10, 8 ]

# scale factor of position count
position_factor : [1, 1, 1, 1]

# direction of axis
direction : [1, 1, -1, -1 ]

absolute_2pi_count : [ 1048576, 1024, 4096, 4096 ]
encoder_2pi_count :  [ 921600, 2000, 1000, 1000 ]

# rated current [A]
rated_current_limit : [ 1.0, 5.0, 10.0, 10.0]
# max current [A]
max_target_current :  [ 4.0, 20.0, 40.0, 40.0]

# torque constant [ Nm/A ]
torque_constant : [10.0, 10.0, 5.0, 5.0]

# GAIN
# Pgain [ Nm / rad ]
Pgain : [ 20000.0, 2000.0, 4000.0, 4000.0]
# Dgain [ Nm / rad/sec ]
Dgain : [ 100.0, 50.0, 50.0, 50.0]
# Igain [ Nm / (rad*src) ]
Igain : [  2, 10, 10, 10]

# [ ohm ]
motor_resistance : [1.0, 1.0, 2.0, 2.0]

# [ K/W ]
motor_thermal_resistance : [2.0, 2.0, 2.0, 2.0]

# [ J/K ]
motor_heat_capacity : [100.0, 100.0, 100.0, 100.0]
